# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/0/Midget/SKL/SKL_Zed_PS_SPI/SKL_Zed_PS_SPI.srcs/sources_1/bd/Zed_SPI/ip/Zed_SPI_xbar_2/Zed_SPI_xbar_2.xci
# IP: The module: 'Zed_SPI_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/0/Midget/SKL/SKL_Zed_PS_SPI/SKL_Zed_PS_SPI.gen/sources_1/bd/Zed_SPI/ip/Zed_SPI_xbar_2/Zed_SPI_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zed_SPI_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/0/Midget/SKL/SKL_Zed_PS_SPI/SKL_Zed_PS_SPI.srcs/sources_1/bd/Zed_SPI/ip/Zed_SPI_xbar_2/Zed_SPI_xbar_2.xci
# IP: The module: 'Zed_SPI_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/0/Midget/SKL/SKL_Zed_PS_SPI/SKL_Zed_PS_SPI.gen/sources_1/bd/Zed_SPI/ip/Zed_SPI_xbar_2/Zed_SPI_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zed_SPI_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
