set_property IOSTANDARD LVCMOS33 [get_ports o_SPI_CLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports i_SPI_MISO_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_SPI_CS_0]
set_property IOSTANDARD LVCMOS33 [get_ports o_SPI_MOSI_0]
set_property PACKAGE_PIN Y11 [get_ports o_SPI_CLK_0]
set_property PACKAGE_PIN AA11 [get_ports o_SPI_CS_0]
set_property PACKAGE_PIN AB11 [get_ports o_SPI_MOSI_0]
set_property PACKAGE_PIN AB10 [get_ports i_SPI_MISO_0]

set_property IOSTANDARD LVCMOS33 [get_ports {o_GPIO_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_GPIO_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_GPIO_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_GPIO_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_GPIO_0[0]}]

set_property PACKAGE_PIN W6 [get_ports {o_GPIO_0[4]}]
set_property PACKAGE_PIN V4 [get_ports {o_GPIO_0[3]}]
set_property PACKAGE_PIN V5 [get_ports {o_GPIO_0[2]}]
set_property PACKAGE_PIN W7 [get_ports {o_GPIO_0[1]}]
set_property PACKAGE_PIN V7 [get_ports {o_GPIO_0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports o_SPI_CLK_1]
set_property IOSTANDARD LVCMOS33 [get_ports i_SPI_MISO_1]
set_property IOSTANDARD LVCMOS33 [get_ports o_SPI_CS_1]
set_property IOSTANDARD LVCMOS33 [get_ports o_SPI_MOSI_1]
set_property PACKAGE_PIN AB7 [get_ports o_SPI_CLK_1]
set_property PACKAGE_PIN T6 [get_ports i_SPI_MISO_1]
set_property PACKAGE_PIN AB6 [get_ports o_SPI_CS_1]
set_property PACKAGE_PIN R6 [get_ports o_SPI_MOSI_1]



set_property IOSTANDARD LVCMOS33 [get_ports {o_LED_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_LED_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_LED_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_LED_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_LED_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_LED_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_LED_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_LED_0[0]}]
set_property PACKAGE_PIN T22 [get_ports {o_LED_0[0]}]
set_property PACKAGE_PIN T21 [get_ports {o_LED_0[1]}]
set_property PACKAGE_PIN U22 [get_ports {o_LED_0[2]}]
set_property PACKAGE_PIN U21 [get_ports {o_LED_0[3]}]
set_property PACKAGE_PIN V22 [get_ports {o_LED_0[4]}]
set_property PACKAGE_PIN W22 [get_ports {o_LED_0[5]}]
set_property PACKAGE_PIN U19 [get_ports {o_LED_0[6]}]
set_property PACKAGE_PIN U14 [get_ports {o_LED_0[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports i_Over_GPIO_0]
set_property PACKAGE_PIN W5 [get_ports i_Over_GPIO_0]


