# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zed_PSPL.xdc

# Block Designs: bd/Zed_SPI/Zed_SPI.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI || ORIG_REF_NAME==Zed_SPI} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_PL_SPI_ADAR_v1_0_0_0/Zed_SPI_PL_SPI_ADAR_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_PL_SPI_ADAR_v1_0_0_0 || ORIG_REF_NAME==Zed_SPI_PL_SPI_ADAR_v1_0_0_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_PL_SPI_ADF4159_v1_0_0_0/Zed_SPI_PL_SPI_ADF4159_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_PL_SPI_ADF4159_v1_0_0_0 || ORIG_REF_NAME==Zed_SPI_PL_SPI_ADF4159_v1_0_0_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_processing_system7_0_0/Zed_SPI_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_processing_system7_0_0 || ORIG_REF_NAME==Zed_SPI_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_xbar_0/Zed_SPI_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_xbar_0 || ORIG_REF_NAME==Zed_SPI_xbar_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_ps7_0_axi_periph_4/Zed_SPI_ps7_0_axi_periph_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_ps7_0_axi_periph_4 || ORIG_REF_NAME==Zed_SPI_ps7_0_axi_periph_4} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_rst_ps7_0_100M_0/Zed_SPI_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_rst_ps7_0_100M_0 || ORIG_REF_NAME==Zed_SPI_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_PL_SPI_DDS_v1_0_0_0/Zed_SPI_PL_SPI_DDS_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_PL_SPI_DDS_v1_0_0_0 || ORIG_REF_NAME==Zed_SPI_PL_SPI_DDS_v1_0_0_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_rst_ps7_0_100M_1_0/Zed_SPI_rst_ps7_0_100M_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_rst_ps7_0_100M_1_0 || ORIG_REF_NAME==Zed_SPI_rst_ps7_0_100M_1_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_clk_wiz_0_0/Zed_SPI_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_clk_wiz_0_0 || ORIG_REF_NAME==Zed_SPI_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_axi_dma_0/Zed_SPI_axi_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_axi_dma_0 || ORIG_REF_NAME==Zed_SPI_axi_dma_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_axi_mem_intercon_0/Zed_SPI_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_axi_mem_intercon_0 || ORIG_REF_NAME==Zed_SPI_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_axi_gpio_0_0/Zed_SPI_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_axi_gpio_0_0 || ORIG_REF_NAME==Zed_SPI_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_LED_Connector_v1_0_0_0/Zed_SPI_LED_Connector_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_LED_Connector_v1_0_0_0 || ORIG_REF_NAME==Zed_SPI_LED_Connector_v1_0_0_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_PL_SPI_ADC_MasterStr_0_0/Zed_SPI_PL_SPI_ADC_MasterStr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_PL_SPI_ADC_MasterStr_0_0 || ORIG_REF_NAME==Zed_SPI_PL_SPI_ADC_MasterStr_0_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_auto_pc_0/Zed_SPI_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_auto_pc_0 || ORIG_REF_NAME==Zed_SPI_auto_pc_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_auto_pc_1/Zed_SPI_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_auto_pc_1 || ORIG_REF_NAME==Zed_SPI_auto_pc_1} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_auto_us_0/Zed_SPI_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_auto_us_0 || ORIG_REF_NAME==Zed_SPI_auto_us_0} -quiet] -quiet

# XDC: d:/Midget_Ws/FPGA/SKL/SKL_SPI_PL_Env/SKL_Zed_PS_SPI.gen/sources_1/bd/Zed_SPI/Zed_SPI_ooc.xdc
