# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zed_PSPL.xdc

# Block Designs: bd/Zed_SPI/Zed_SPI.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI || ORIG_REF_NAME==Zed_SPI} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_processing_system7_0_0/Zed_SPI_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_processing_system7_0_0 || ORIG_REF_NAME==Zed_SPI_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_ps7_0_axi_periph_0/Zed_SPI_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zed_SPI_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_rst_ps7_0_100M_0/Zed_SPI_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_rst_ps7_0_100M_0 || ORIG_REF_NAME==Zed_SPI_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_PL_SPI_v1_0_0_0/Zed_SPI_PL_SPI_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_PL_SPI_v1_0_0_0 || ORIG_REF_NAME==Zed_SPI_PL_SPI_v1_0_0_0} -quiet] -quiet

# IP: bd/Zed_SPI/ip/Zed_SPI_auto_pc_0/Zed_SPI_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Zed_SPI_auto_pc_0 || ORIG_REF_NAME==Zed_SPI_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/0/Midget/SKL/SKL_Zed_PS_SPI/SKL_Zed_PS_SPI.gen/sources_1/bd/Zed_SPI/Zed_SPI_ooc.xdc
