# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/labish/Midget/SKL/SKL_SPI_PL_Env/SKL_Zed_PS_SPI.srcs/sources_1/bd/Zed_SPI/ip/Zed_SPI_processing_system7_0_0/Zed_SPI_processing_system7_0_0.xci
# IP: The module: 'Zed_SPI_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/labish/Midget/SKL/SKL_SPI_PL_Env/SKL_Zed_PS_SPI.gen/sources_1/bd/Zed_SPI/ip/Zed_SPI_processing_system7_0_0/Zed_SPI_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zed_SPI_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/labish/Midget/SKL/SKL_SPI_PL_Env/SKL_Zed_PS_SPI.srcs/sources_1/bd/Zed_SPI/ip/Zed_SPI_processing_system7_0_0/Zed_SPI_processing_system7_0_0.xci
# IP: The module: 'Zed_SPI_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/labish/Midget/SKL/SKL_SPI_PL_Env/SKL_Zed_PS_SPI.gen/sources_1/bd/Zed_SPI/ip/Zed_SPI_processing_system7_0_0/Zed_SPI_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zed_SPI_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
